spring.application.name=fitness-tracker
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:5432/postgres?user=postgres.kcfyxmedtljxgfkurazr&password=9t*,2!trqm4wvWS
spring.security.oauth2.resourceserver.jwt.issuer-uri=SUPABASE_ISSUER_URI 
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
server.forward-headers-strategy=native
#The line same-site: allows to send cookies between different sites and the one below means but only over HTTPS
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
spring.datasource.hikari.maximum-pool-size=45
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=540000
spring.datasource.hikari.connection-timeout=30000